import { useState, useEffect } from 'react';
import { generatePlots } from '../../services/api.js';

export default function AiPlots({ stats, plan, userData, completedDays }) {
  const [charts, setCharts] = useState([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  const fetchPlots = async () => {
    setLoading(true);
    setError(null);
    console.log('[AiPlots] Fetching plots with stats:', stats);
    try {
      const result = await generatePlots({ stats, plan, userData, completedDays });
      console.log('[AiPlots] Got result:', result.charts?.length, 'charts');
      setCharts(result.charts || []);
    } catch (e) {
      console.error('[AiPlots] Error:', e);
      setError(e.message);
    } finally {
      setLoading(false);
    }
  };

  // Auto-fetch on first render when stats are available
  useEffect(() => {
    if (stats && !loading && charts.length === 0 && !error) {
      fetchPlots();
    }
  }, [stats]);

  if (loading) {
    return (
      <div style={{ marginTop: 20 }}>
        <div style={{ fontWeight: 700, fontSize: 16, marginBottom: 12 }}>AI-Generated Charts</div>
        <p style={{ fontSize: 13, color: 'var(--text-muted)', marginBottom: 8 }}>
          Gemini is painting your performance data...
        </p>
        <div className="spinner" />
      </div>
    );
  }

  if (error) {
    return (
      <div style={{ marginTop: 20 }}>
        <div style={{ fontWeight: 700, fontSize: 16, marginBottom: 12 }}>AI-Generated Charts</div>
        <div className="card" style={{ borderColor: 'var(--accent-warm)' }}>
          <p style={{ color: 'var(--accent-warm)', fontSize: 13 }}>{error}</p>
        </div>
        <button className="btn btn-primary btn-full" style={{ marginTop: 8 }} onClick={fetchPlots}>
          Retry
        </button>
      </div>
    );
  }

  if (charts.length === 0) {
    return null;
  }

  return (
    <div style={{ marginTop: 20 }}>
      <div style={{ fontWeight: 700, fontSize: 16, marginBottom: 12 }}>AI-Generated Charts</div>
      <p style={{ fontSize: 11, color: 'var(--text-muted)', marginBottom: 12 }}>
        Visualizations generated by Google Gemini -- unique every time
      </p>
      {charts.map((svg, i) => (
        <div
          key={i}
          className="card fade-in"
          style={{
            marginBottom: 12,
            padding: 8,
            animationDelay: `${i * 0.15}s`,
            overflow: 'hidden',
          }}
          dangerouslySetInnerHTML={{ __html: svg }}
        />
      ))}
      <button
        className="btn btn-secondary btn-full"
        style={{ marginTop: 4 }}
        onClick={fetchPlots}
      >
        Regenerate Charts
      </button>
    </div>
  );
}
